### ISSUE TITLE
Error in line 157 of OptSpace

### ISSUE THREAD

**Issue by halidaee** [cran/ROptSpace#1]
Line 157 has the following code:   `S0 = diag(svdEt$d)[1:r]`. However, the output of svdEt$d is already the vector of the diagonal; therefore, this transforms the vector into a matrix. Consequently, S0 becomes a vector containing [<the first singular value>, 0, 0]. This can be fixed by changing the code to just  `S0 = svdEt$d[1:r]`.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the `DESCRIPTION` file for the package authors. Thanks!
