### ISSUE TITLE
guess_rank issue

### ISSUE THREAD

**Issue by halidaee** [cran/ROptSpace#2]
Occasionally, depending on the matrix (even for noisy social network data), guess_rank will output 1 as its guessed rank. This messes with dimensions of future products created in OptSpace based on r, whose value is determined by guess_rank. When r=1, other variables created become vectors instead of matrices, eventually causing `aux_getoptS` to fail due to improper dimensions. Having `r <- max(guess_rank(M_E,nnZ.E), 2)` could remedy this.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the `DESCRIPTION` file for the package authors. Thanks!
